name: Manual GAS Deploy

on:
  workflow_dispatch:
    inputs:
      project:
        description: 'デプロイするプロジェクト名'
        required: true
        default: 'apps/spreadsheet-hello-message'
        type: choice
        options:
        - apps/spreadsheet-hello-message
      environment:
        description: 'デプロイ環境'
        required: true
        default: 'development'
        type: choice
        options:
        - development
        - production
      description:
        description: 'デプロイの説明'
        required: true
        default: 'GitHub Actionsによる自動デプロイ'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    defaults:
      run:
        working-directory: ${{ inputs.project }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: npm

      - name: Install Clasp
        run: npm install -g @google/clasp

      - name: Create .clasprc.json
        run: |
          cat << EOS > ~/.clasprc.json
          {
            "token": {
              "access_token": "${{ secrets.ACCESS_TOKEN }}",
              "refresh_token": "${{ secrets.REFRESH_TOKEN }}",
              "scope": "https://www.googleapis.com/auth/drive.file https://www.googleapis.com/auth/logging.read https://www.googleapis.com/auth/script.deployments https://www.googleapis.com/auth/service.management https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/drive.metadata.readonly https://www.googleapis.com/auth/script.projects https://www.googleapis.com/auth/script.webapp.deploy openid https://www.googleapis.com/auth/userinfo.email",
              "token_type": "Bearer",
              "id_token": "${{ secrets.ID_TOKEN }}",
              "expiry_date": "${{ secrets.EXPIRY_DATE }}"
            },
            "oauth2ClientSettings": {
              "clientId": "${{ secrets.CLIENT_ID }}",
              "clientSecret": "${{ secrets.CLIENT_SECRET }}",
              "redirectUri": "http://localhost"
            },
            "isLocalCreds": false
          }
          EOS

      - name: Create .clasp.json with environment-specific values
        run: |
          echo "{ \"scriptId\": \"${{ secrets.SCRIPT_ID }}\", \"rootDir\": \".\", \"parentId\": [\"${{ secrets.PARENT_ID }}\"] }" > .clasp.json
          cat .clasp.json | jq 'del(.scriptId, .parentId) + {scriptId: "***", parentId: ["***"]}' || echo "Created .clasp.json (hiding sensitive info)"

      - name: Push to Google Apps Script
        run: clasp push -f

      - name: Deployment Information
        run: |
          echo "プロジェクト： ${{ inputs.project }}"
          echo "環境： ${{ inputs.environment }}"
          echo "デプロイの説明： ${{ inputs.description }}"
          echo "スクリプトID： ***（セキュリティのため非表示）"
          echo "デプロイ完了"
